exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex('users')
    .del()
    .then(() =>
      // Inserts seed entries
      knex('users').insert([
        {
          id: 1,
          firstname: 'Kristy',
          last_name: 'Lees',
          email: 'kristy@gmail.com',
          password: 'password',
          cohort_id: null,
          role_id: 1,
        },
        {
          id: 2,
          firstname: 'Eudora',
          last_name: 'Bernier',
          email: 'ebernier1@dyndns.org',
          password: 'IjnRNh',
          cohort_id: null,
          role_id: 2,
        },
        {
          id: 3,
          firstname: 'Drusie',
          last_name: 'Enrietto',
          email: 'denrietto2@cbslocal.com',
          password: 'IIXvmeCN5Z',
          cohort_id: null,
          role_id: 2,
        },
        {
          id: 4,
          firstname: 'Rosamund',
          last_name: 'Hurry',
          email: 'rhurry3@ovh.net',
          password: 'z08ltC',
          cohort_id: null,
          role_id: 2,
        },
        {
          id: 5,
          firstname: 'Sherill',
          last_name: 'Pithie',
          email: 'spithie4@imgur.com',
          password: 'mEe88dRQtc7',
          cohort_id: 2,
          role_id: 2,
        },
        {
          id: 6,
          firstname: 'Ralina',
          last_name: 'Dumingo',
          email: 'rdumingo5@wp.com',
          password: 'erGkh9l67FC',
          cohort_id: null,
          role_id: 2,
        },
        {
          id: 7,
          firstname: 'Kermie',
          last_name: 'Cowwell',
          email: 'kcowwell6@dailymail.co.uk',
          password: 'F2Vg7OssaHkL',
          cohort_id: null,
          role_id: 2,
        },
        {
          id: 8,
          firstname: 'Kaylyn',
          last_name: 'Stow',
          email: 'kstow7@state.tx.us',
          password: 'xL4f9cVZO',
          cohort_id: null,
          role_id: 2,
        },
        {
          id: 9,
          firstname: 'Lowrance',
          last_name: 'Christiensen',
          email: 'lchristiensen8@over-blog.com',
          password: 'vGDIlkuvQ',
          cohort_id: null,
          role_id: 2,
        },
        {
          id: 10,
          firstname: 'Roxy',
          last_name: 'Burrus',
          email: 'rburrus9@yolasite.com',
          password: 'qWMf20mph',
          cohort_id: null,
          role_id: 2,
        },
        {
          id: 11,
          firstname: 'Barr',
          last_name: 'Suermeiers',
          email: 'bsuermeiers0@economist.com',
          password: 'mTVq6VjfcH',
          cohort_id: 4,
          role_id: 3,
        },
        {
          id: 12,
          firstname: 'Marijn',
          last_name: 'Evett',
          email: 'mevett1@economist.com',
          password: '7Zx02ZjJh',
          cohort_id: 2,
          role_id: 3,
        },
        {
          id: 13,
          firstname: 'Jessy',
          last_name: 'Cowill',
          email: 'jcowill2@4shared.com',
          password: 'i2mdw1',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 14,
          firstname: 'Stefania',
          last_name: 'Sarfati',
          email: 'ssarfati3@infoseek.co.jp',
          password: 'ywb968Uodsw',
          cohort_id: 5,
          role_id: 3,
        },
        {
          id: 15,
          firstname: 'Grazia',
          last_name: 'Meeking',
          email: 'gmeeking4@gravatar.com',
          password: '633GsE',
          cohort_id: 7,
          role_id: 3,
        },
        {
          id: 16,
          firstname: 'Shelby',
          last_name: 'Wadie',
          email: 'swadie5@cbsnews.com',
          password: '0zqtpU2',
          cohort_id: 7,
          role_id: 3,
        },
        {
          id: 17,
          firstname: 'Griswold',
          last_name: 'Lamplugh',
          email: 'glamplugh6@wp.com',
          password: 'nOhqbpVsb',
          cohort_id: 5,
          role_id: 3,
        },
        {
          id: 18,
          firstname: 'Sherman',
          last_name: 'MacCarrick',
          email: 'smaccarrick7@yelp.com',
          password: '3ESIiWf5vZp',
          cohort_id: 4,
          role_id: 3,
        },
        {
          id: 19,
          firstname: 'Donaugh',
          last_name: 'Callacher',
          email: 'dcallacher8@nymag.com',
          password: 'iVOKuS5',
          cohort_id: 3,
          role_id: 3,
        },
        {
          id: 20,
          firstname: 'Nari',
          last_name: 'Feldstein',
          email: 'nfeldstein9@ehow.com',
          password: 'wmGWHy8I',
          cohort_id: 6,
          role_id: 3,
        },
        {
          id: 21,
          firstname: 'Jodee',
          last_name: 'Haliburton',
          email: 'jhaliburtonk@domainmarket.com',
          password: 'cpdaddQVkB',
          cohort_id: 7,
          role_id: 3,
        },
        {
          id: 22,
          firstname: 'Eduino',
          last_name: 'Risen',
          email: 'erisenl@youtu.be',
          password: 'cujylyaCP48g',
          cohort_id: 2,
          role_id: 3,
        },
        {
          id: 23,
          firstname: 'Lotte',
          last_name: 'Strover',
          email: 'lstroverm@psu.edu',
          password: '6H4SAOeCp',
          cohort_id: 3,
          role_id: 3,
        },
        {
          id: 24,
          firstname: 'Trisha',
          last_name: 'Dellatorre',
          email: 'tdellatorren@diigo.com',
          password: '2jL2g8BEvaJu',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 25,
          firstname: 'Ophelia',
          last_name: 'Kingzett',
          email: 'okingzetto@comsenz.com',
          password: '6IVsGTmdd7DM',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 26,
          firstname: 'Blaine',
          last_name: 'Dyton',
          email: 'bdytonp@weather.com',
          password: 'btHc3R5g',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 27,
          firstname: 'Dominica',
          last_name: 'Foxley',
          email: 'dfoxleyq@webs.com',
          password: '3PFcZq2mhU4',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 28,
          firstname: 'Marjory',
          last_name: 'Lipsett',
          email: 'mlipsettr@google.com.br',
          password: 'VG9eVyX',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 29,
          firstname: 'Dian',
          last_name: 'MacAdam',
          email: 'dmacadams@google.ru',
          password: 'nntrn7LFaLyi',
          cohort_id: 4,
          role_id: 3,
        },
        {
          id: 30,
          firstname: 'Cayla',
          last_name: 'Maypes',
          email: 'cmaypest@sphinn.com',
          password: 'dWAAi5z',
          cohort_id: 7,
          role_id: 3,
        },
        {
          id: 31,
          firstname: 'Emmey',
          last_name: 'Seaward',
          email: 'eseawardu@yelp.com',
          password: '9oTTOPd2qD',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 32,
          firstname: 'Brennan',
          last_name: 'Cheak',
          email: 'bcheakv@netvibes.com',
          password: 'pydlo0iQ',
          cohort_id: 7,
          role_id: 3,
        },
        {
          id: 33,
          firstname: 'Charlie',
          last_name: 'Hoyles',
          email: 'choylesw@ox.ac.uk',
          password: 'VctPGhP6InL6',
          cohort_id: 7,
          role_id: 3,
        },
        {
          id: 34,
          firstname: 'Nilson',
          last_name: 'Heel',
          email: 'nheelx@stumbleupon.com',
          password: '1B1QOKVA',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 35,
          firstname: 'Robby',
          last_name: 'Thamelt',
          email: 'rthamelty@newsvine.com',
          password: 'NBnsII0G',
          cohort_id: 6,
          role_id: 3,
        },
        {
          id: 36,
          firstname: 'Olva',
          last_name: 'Bearns',
          email: 'obearnsz@hao123.com',
          password: 'IZsSkhs',
          cohort_id: 4,
          role_id: 3,
        },
        {
          id: 37,
          firstname: 'Duke',
          last_name: 'Gretham',
          email: 'dgretham10@quantcast.com',
          password: 'd7yKNXd',
          cohort_id: 5,
          role_id: 3,
        },
        {
          id: 38,
          firstname: 'Toby',
          last_name: 'Clappison',
          email: 'tclappison11@tuttocitta.it',
          password: 'APBfQQ9Ka',
          cohort_id: 6,
          role_id: 3,
        },
        {
          id: 39,
          firstname: 'Maitilde',
          last_name: 'Etty',
          email: 'metty12@bing.com',
          password: 'y4XU0N',
          cohort_id: 4,
          role_id: 3,
        },
        {
          id: 40,
          firstname: 'Raquel',
          last_name: 'Zuenelli',
          email: 'rzuenelli13@technorati.com',
          password: 'SJJdN0GpS9',
          cohort_id: 4,
          role_id: 3,
        },
        {
          id: 41,
          firstname: 'Fanechka',
          last_name: 'Canon',
          email: 'fcanona@cisco.com',
          password: 'U0ebXjVR',
          cohort_id: 3,
          role_id: 3,
        },
        {
          id: 42,
          firstname: 'Randi',
          last_name: 'Ghest',
          email: 'rghestb@wix.com',
          password: 'WYlbmfxfVMZs',
          cohort_id: 2,
          role_id: 3,
        },
        {
          id: 43,
          firstname: 'Jacob',
          last_name: 'Wikey',
          email: 'jwikeyc@blogs.com',
          password: 'cDmQZZAWnHIO',
          cohort_id: 5,
          role_id: 3,
        },
        {
          id: 44,
          firstname: 'Janie',
          last_name: 'Cowdry',
          email: 'jcowdryd@cdc.gov',
          password: 'tPJuEmo2AsuL',
          cohort_id: 6,
          role_id: 3,
        },
        {
          id: 45,
          firstname: 'Thayne',
          last_name: 'Hearnah',
          email: 'thearnahe@linkedin.com',
          password: 'pbKMRQfB',
          cohort_id: 1,
          role_id: 3,
        },
        {
          id: 46,
          firstname: 'Hanni',
          last_name: 'Mapstone',
          email: 'hmapstonef@blog.com',
          password: 'AJVCXbxG',
          cohort_id: 5,
          role_id: 3,
        },
        {
          id: 47,
          firstname: 'Monty',
          last_name: 'Dossit',
          email: 'mdossitg@dailymotion.com',
          password: 'n8T7LB4nm',
          cohort_id: 5,
          role_id: 3,
        },
        {
          id: 48,
          firstname: 'Genni',
          last_name: 'Iacobucci',
          email: 'giacobuccih@princeton.edu',
          password: 'XPoxHz',
          cohort_id: 2,
          role_id: 3,
        },
        {
          id: 49,
          firstname: 'Herta',
          last_name: 'Meth',
          email: 'hmethi@pinterest.com',
          password: 'iGgDmfhgpL2r',
          cohort_id: 6,
          role_id: 3,
        },
        {
          id: 50,
          firstname: 'Allison',
          last_name: 'Hould',
          email: 'ahouldj@trellian.com',
          password: 'zclKFCaV2',
          cohort_id: 5,
          role_id: 3,
        },
      ])
    )
}
